# Generated by Django 5.2.16 on 2026-07-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_mcp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPToolConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("tags", models.CharField(blank=True, default="", max_length=500)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "MCP Tool",
                "verbose_name_plural": "MCP Tools",
                "ordering": ["name"],
            },
        ),
    ]
