# Generated by Django 5.2.16 on 2026-07-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_mcp", "0002_add_mcptoolconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcredential",
            name="global_access",
            field=models.BooleanField(
                default=False,
                help_text="Allow this credential to access all users' objects. Only available for superuser credentials.",
            ),
        ),
    ]
